# Kubernete agent for a prefect server deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-agent-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-agent-1
  template:
    metadata:
      labels:
        app: kubernetes-agent-1
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - args:
        - prefect agent kubernetes start
        command:
        - /bin/bash
        - -c
        env:
        - name: PREFECT__CLOUD__API
          value: {{ include "prefect-server.apollo-api-url" . }}
        - name: NAMESPACE
            value: {{ .Release.Namespace }}
        - name: PREFECT__CLOUD__AGENT__LABELS
          value: '["gpu-server-1"]'
        - name: JOB_MEM_REQUEST
          value: ''
        - name: JOB_MEM_LIMIT
          value: ''
        - name: JOB_CPU_REQUEST
          value: ''
        - name: JOB_CPU_LIMIT
          value: ''
        - name: IMAGE_PULL_POLICY
          value: 'Always'
        - name: SERVICE_ACCOUNT_NAME
          value: {{ include "prefect-server.serviceAccountName" . }}
        - name: PREFECT__BACKEND
          value: server
        - name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
          value: http://0.0.0.0:8080
        - name: PREFECT__CLOUD__TENANT_ID
          value: ''
        image: prefecthq/prefect:1.1.0-python3.9
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 40
        name: agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubernetes-agent-1-rbac
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - events
  - pods
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-agent-1-rbac
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubernetes-agent-1-rbac
subjects:
- kind: ServiceAccount
  name: default

